name: My pipeline for DevOps Crash Course

on: 
  push:
    branches: [master]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  ci_pipline:
    runs-on: ubuntu-latest
    steps:
    - name: Print my name
      run: echo "Liubchenko Denys"
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
    - name: Fix permissions
      run: |
        chmod -c -R +rX "_site/" | while read line; do
          echo "::warning title=Invalid file permissions automatically fixed::$line"
        done
    - name: Upload Pages artifact 
      uses: actions/upload-pages-artifact@v2
  cd_pipeline:
    needs: [ci_pipline]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Print my name
      run: echo "Liubchenko Denys"
    - name: Deploy page
      id: deployment
      uses: actions/deploy-pages@v2 
