name: My pipeline for DevOps Crash Course

on: 
  push:
    branches: [master]

jobs:
  ci_pipline:
    runs-on: ubuntu-latest
    steps:
    - name: Print my name
      run: echo "Liubchenko Denys"
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
